stages:
  - build

compile:
  image: golang:1.8.1
  stage: build
  script:
    - ls -lah
    - ln -s /builds /go/src/github.com
    - cd /go/src/github.com/prometheus/prometheus
    - make build
    # - /bin/bash -c "sleep infinity"
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - build/

tar:
  stage: package
  image: golang:1.8.1
  script:
    - make tarball
  dependencies:
    - compile
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - build/
