apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: prometheus
    spec:
      containers:
      - name: prometheus
        image: registry.cncf.ci/prometheus/prometheus:ci-master.8e480b94.6100
        command: ["bash", "-c", "/tests/promselftest"]
        env:
        - name: PROMETHEUS_SERVICE_HOST
          value: "prometheus.local"
        - name: PROMETHEUS_SERVICE_PORT
          value: "9090"
      restartPolicy: "Never"
